### ISSUE TITLE
CloudFront Response policies

### ISSUE THREAD

**Issue by achrafsouk** [satellytes/learning-caching-headers#1]
Using the new capability of CloudFront, you can natively remove the Age header, and replace the cached Date header with a generated one. I suggest you update your blog.

https://aws.amazon.com/about-aws/whats-new/2023/01/amazon-cloudfront-supports-removal-response-headers/

**Comment by feedm3** [comment]
Thanks for the notice!

As this example uses a function on CloudFront anyways to modify the header, I think it is better to keep it like it is and have all header modification in there: https://github.com/satellytes/learning-caching-headers/blob/main/serverless.yml#L35
But still good to know that there is an alternative now.

Depending on the requirements you might even not want to delete the `age` header at all. It's totally fine to leave it. See some comments about this topic here: https://www.reddit.com/r/aws/comments/sviapt/comment/hxhmwxq/

**Comment by achrafsouk** [comment]
What other header modification you are doing? The code only changes Date header, which could be done with this new feature. If you remove the Date header using the response policy, CloudFront will removed the Date header in the cached version, and will add a new Date header with the value of Now.
